name: background_ble_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation:
  freezed_annotation:
  rxdart:
  flutter_blue_plus:
  drift:
  drift_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  riverpod_generator:
  build_runner:
  custom_lint:
  riverpod_lint:
  freezed:
  drift_dev:

flutter:
  uses-material-design: true
